# unicode definitions
SPACE = 0x0020
PLUS_SIGN = 0x002B
FULL_STOP = 0x002E
BULLET_OPERATOR = 0x2219
MIDDLE_DOT = 0x00B7
BOX_DRAWINGS_LIGHT_TRIPLE_DASH_VERTICAL = 0x2506
BOX_DRAWINGS_LIGHT_QUADRUPLE_DASH_HORIZONTAL = 0x2508
BOX_DRAWINGS_DOUBLE_HORIZONTAL = 0x2550
BOX_DRAWINGS_DOUBLE_VERTICAL = 0x2551
BOX_DRAWINGS_DOUBLE_DOWN_RIGHT = 0x2554
BOX_DRAWINGS_DOUBLE_DOWN_LEFT = 0x2557
BOX_DRAWINGS_DOUBLE_UP_RIGHT = 0x255A
BOX_DRAWINGS_DOUBLE_UP_LEFT = 0x255D
BOX_DRAWINGS_VERTICAL_SINGLE_RIGHT_DOUBLE = 0x255E
BOX_DRAWINGS_DOUBLE_VERTICAL_RIGHT = 0x2560
BOX_DRAWINGS_VERTICAL_SINGLE_LEFT_DOUBLE = 0x2561
BOX_DRAWINGS_DOUBLE_VERTICAL_LEFT = 0x2563
BOX_DRAWINGS_DOUBLE_DOWN_HORIZONTAL = 0x2566
BOX_DRAWINGS_DOWN_DOUBLE_HORIZONTAL_SINGLE = 0x2565
BOX_DRAWINGS_UP_DOUBLE_HORIZONTAL_SINGLE = 0x2568
BOX_DRAWINGS_DOUBLE_UP_HORIZONTAL = 0x2569
BOX_DRAWINGS_DOUBLE_VERTICAL_HORIZONTAL = 0x256C
WHITE_SQUARE_CONTAINING_BLACK_SMALL_SQUARE = 0x25A3


# Basic multilingual plane private use area: 6400 code points
PUA = 0xE000

# graphical tile codepoints
COLUMN = WHITE_SQUARE_CONTAINING_BLACK_SMALL_SQUARE
WALL = SPACE
WALL_L = BOX_DRAWINGS_VERTICAL_SINGLE_LEFT_DOUBLE
WALL_A = BOX_DRAWINGS_UP_DOUBLE_HORIZONTAL_SINGLE
WALL_R = BOX_DRAWINGS_VERTICAL_SINGLE_RIGHT_DOUBLE
WALL_B = BOX_DRAWINGS_DOWN_DOUBLE_HORIZONTAL_SINGLE
WALL_LR = BOX_DRAWINGS_DOUBLE_HORIZONTAL
WALL_AB = BOX_DRAWINGS_DOUBLE_VERTICAL
WALL_RB = BOX_DRAWINGS_DOUBLE_DOWN_RIGHT
WALL_LB = BOX_DRAWINGS_DOUBLE_DOWN_LEFT
WALL_AR = BOX_DRAWINGS_DOUBLE_UP_RIGHT
WALL_LA = BOX_DRAWINGS_DOUBLE_UP_LEFT
WALL_ARB = BOX_DRAWINGS_DOUBLE_VERTICAL_RIGHT
WALL_LAB = BOX_DRAWINGS_DOUBLE_VERTICAL_LEFT
WALL_LRB = BOX_DRAWINGS_DOUBLE_DOWN_HORIZONTAL
WALL_LAR = BOX_DRAWINGS_DOUBLE_UP_HORIZONTAL
WALL_LARB = BOX_DRAWINGS_DOUBLE_VERTICAL_HORIZONTAL
DOOR = PLUS_SIGN
DOOR_H = DOOR#BOX_DRAWINGS_LIGHT_QUADRUPLE_DASH_HORIZONTAL
DOOR_V = DOOR#BOX_DRAWINGS_LIGHT_TRIPLE_DASH_VERTICAL

# wouldn't it be nice to allocate graphical tile codes in the private use area?
# the 6400 slots in the BMP private use area should be more than we need

